### ISSUE TITLE
IE8 compat

### ISSUE THREAD

**Issue by th3fallen** [blakeembrey/dombars#34]
As much as it pains me to to do this bug report but is there any possible way to make this work in IE8?

**Comment by blakeembrey** [comment]
@th3fallen Yeah, that sounds like fun. I'll look at it tonight, it all uses fairly basic DOM APIs so I can't imagine being difficult to get working.

**Comment by th3fallen** [comment]
<3 this is the only error i see http://take.ms/bKMBv

**Comment by blakeembrey** [comment]
@th3fallen Could you try the latest master? I just pushed some updated but can't run my test suite since chai doesn't work in IE8.

**Comment by th3fallen** [comment]
@blakeembrey firstly thanks for the amazingly fast update, but you where close here's the new issue.

https://monosnap.com/image/D1qdSwqW91XRXJXKabG5rJzFOy5Igc

**Comment by blakeembrey** [comment]
@th3fallen Looks like that code is out of my control and part of `htmlparser2`. I'll look at opening a PR against it tonight. For now you should be able to find a simple `Array.prototype.lastIndexOf` polyfill.

**Comment by th3fallen** [comment]
i'll check on that thanks

**Comment by th3fallen** [comment]
sorted that out, now i've got this beauty https://monosnap.com/image/uZbXnQlWdl83nlA4n67okwFqbMezQ0

**Comment by blakeembrey** [comment]
@th3fallen Ok, I'll get some VMs set up tonight to work on that.

**Comment by th3fallen** [comment]
Sounds wonderful also for anyone interested here's the polyfill i used for the lastIndexOf

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf

**Comment by blakeembrey** [comment]
@th3fallen I think it's finally complete in IE (aside from data binding a `type` attribute of an input - but that's another story). Let me know how it goes for you.

**Comment by th3fallen** [comment]
Thanks I'll give it a shot on Monday when I'm back in the office.Thanks a
ton for your quick support

**Comment by th3fallen** [comment]
nope now you get this https://monosnap.com/image/CqO64kgBqcrKaav5uvTdIFEjHN1hvP

**Comment by blakeembrey** [comment]
@th3fallen Hmm, really? It's definitely working for me in IE8. Do you have any more information? What's the template, etc.?

**Comment by th3fallen** [comment]
here's the url where the issue is occurring hopefully that will help.
http://dev.insp.com/phase2/insp-quiz/test-quiz/

**Comment by th3fallen** [comment]
any update or is it on my end?

**Comment by blakeembrey** [comment]
I'm getting a redirect when I hit the url?

**Comment by th3fallen** [comment]
ah sorry we had to change the permalink heres the updated one http://dev.insp.com/phase2/inspquiz/test/

**Comment by blakeembrey** [comment]
Ok, just pushed a new commit. Should resolve the issue, but if there is more please let me know.

**Comment by th3fallen** [comment]
@blakeembrey that one did it, Thanks a ton!

**Comment by th3fallen** [comment]
@blakeembrey  well kind of now i get three answers when there are only two (only in ie 8) im not positive thats dombars fault but it may be as it doesnt occur anywhere else?

**Comment by blakeembrey** [comment]
@th3fallen Do you think you could make a reduced test case for it? Just need something I can debug appropriately and ensure it's not related to anything else on the page.

**Comment by th3fallen** [comment]
@blakeembrey heres a super slimmed one http://dev.insp.com/

**Comment by blakeembrey** [comment]
@th3fallen I was hoping for something off the site with minimal dependency that can replicate the problem. The issue may be related to DOMBars or CSS3PIE, so I was hoping to work out the code your using. Doesn't have to look the same, you can just paste an DOMBars loop into JSFiddle and if it causes the bug in IE8 send that. Thanks!

**Comment by th3fallen** [comment]
@blakeembrey it was an issue on my end i've got it sorted out thanks a million!

**Comment by blakeembrey** [comment]
@th3fallen No problem, I'm glad it worked out! Do you mind if I ask what the issue was?

**Comment by th3fallen** [comment]
@blakeembrey for some reason when i was adding answers to the model in ie8 it was adding an extra empty one. which blew things up when i needed to do an each on them. so i just popped the empty off and did a filter to get rid of any other extras in ie

**Comment by blakeembrey** [comment]
Hmm, interesting. Well, glad it's working now.

**Comment by th3fallen** [comment]
You and me both i was about to pull my hair out. Thanks again for the amazing support.
