### ISSUE TITLE
How deprecated is this?

### ISSUE THREAD

**Issue by ghost** [blakeembrey/dombars#37]
Hi there. Just revisiting this project and saw you've deprecated it. I think this is a great concept and it's something I'm looking to include in a little framework I'm writing. Can you outline any particular difficulties you've run in to and/or alternative solutions that motivated deprecating it? I'd be happy to carry this on as I run across issues incorporating it in to my framework.

**Comment by blakeembrey** [comment]
I would love to continue writing it, but it came down to mostly a time and interest constraint. With the level of interest in the project I couldn't justify spending large swabs of my nights on continual development. I think there are a number of things that can be improved now, and I can leave an outline below of things I still want(ed) to add:
- Implement virtual DOM (https://github.com/Matt-Esch/virtual-dom)
- Emit compilation events (used to have this, but removed for performance issues - basically emitting create element, add content, remove content, add attribute, change, attribute, etc.)
- Implement a plugin architecture (`.use` style for adding custom DOM plugins)
- Implement `setTimeout`, `setInterval` and `setImmediate` in terms of animation frame loop
- Rewrite the html parser to be more lightweight and integrate with handlebars better (currently doing multiple steps with a standalone html parser)
- Better documentation!
- Improve event listener support and performance (currently buggy with multiple levels of nested changes)

If you are genuinely interested in the continued development of the project, I can look at getting it into a better state and see if there is more community interest to continue development as well.

**Comment by ghost** [comment]
Thanks for the outline, sounds great. I'm in great need of a reactive handlebars template solution and this seems more complete / more in my line of thinking than the htmlbars project. I've forked the project and am getting familiar with the code base. If you can take some time to help me along in a few places I'd really appreciate it. What's the best way to contact you with questions (rather than clutter up the issue tracker).

**Comment by blakeembrey** [comment]
No problem. I honestly think the project is in need of a fairly decent refactor to support the enhanced features as my initial implementation sort of just powered through to create the MVP module. If you need a hand with anything, you can email me `hello@blakeembrey.com` or ping me on google hangouts/skype (same username).

**Comment by stevenvachon** [comment]
Perhaps you both will be interested in a [Handlebars-to-React compiler](https://github.com/stevenvachon/handlebars-react-compiler) that I am writing. It should accomplish the goals of this project and in less time since I won't have to write the reactive parts.

**Comment by blakeembrey** [comment]
Cool. I think I'll close this issue now, as I moved on personally to using Angular at work and React in personal projects. React is certainly a much better approach to solving the templating issue (to me).
